apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-app
  labels:
    app: website
  annotations:
    argocd-image-updater.argoproj.io/image-list: website-application=pavan050/website
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/website-application.update-strategy: latest
spec:
  replicas: 3
  selector: 
   matchLabels:
    app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website-application
          image: pavan050/website:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 2000

