apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-app
  labels:
    app: website
spec:
  replicas: 2
  selector: 
   matchLabels:
    app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website-application
          image: pavan050/website:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 2000
